#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CRM")]
	public partial class DataClassesFiltersDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcategory(category instance);
    partial void Updatecategory(category instance);
    partial void Deletecategory(category instance);
    partial void Insertcategories_type(categories_type instance);
    partial void Updatecategories_type(categories_type instance);
    partial void Deletecategories_type(categories_type instance);
    partial void Inserttab_filter(tab_filter instance);
    partial void Updatetab_filter(tab_filter instance);
    partial void Deletetab_filter(tab_filter instance);
    partial void Insertcategory_sub(category_sub instance);
    partial void Updatecategory_sub(category_sub instance);
    partial void Deletecategory_sub(category_sub instance);
    #endregion
		
		public DataClassesFiltersDataContext() : 
				base(global::CRM.Properties.Settings.Default.CRMConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesFiltersDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesFiltersDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesFiltersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesFiltersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<category> categories
		{
			get
			{
				return this.GetTable<category>();
			}
		}
		
		public System.Data.Linq.Table<categories_type> categories_types
		{
			get
			{
				return this.GetTable<categories_type>();
			}
		}
		
		public System.Data.Linq.Table<tab_filter> tab_filters
		{
			get
			{
				return this.GetTable<tab_filter>();
			}
		}
		
		public System.Data.Linq.Table<category_sub> category_subs
		{
			get
			{
				return this.GetTable<category_sub>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.category")]
	public partial class category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_category;
		
		private string _name;
		
		private int _id_categories_types;
		
		private System.Nullable<bool> _show_on_list;
		
		private int _id_tab_filters;
		
		private EntityRef<category_sub> _category_sub;
		
		private EntityRef<categories_type> _categories_type;
		
		private EntityRef<tab_filter> _tab_filter;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_categoryChanging(int value);
    partial void Onid_categoryChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onid_categories_typesChanging(int value);
    partial void Onid_categories_typesChanged();
    partial void Onshow_on_listChanging(System.Nullable<bool> value);
    partial void Onshow_on_listChanged();
    partial void Onid_tab_filtersChanging(int value);
    partial void Onid_tab_filtersChanged();
    #endregion
		
		public category()
		{
			this._category_sub = default(EntityRef<category_sub>);
			this._categories_type = default(EntityRef<categories_type>);
			this._tab_filter = default(EntityRef<tab_filter>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_category", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_category
		{
			get
			{
				return this._id_category;
			}
			set
			{
				if ((this._id_category != value))
				{
					this.Onid_categoryChanging(value);
					this.SendPropertyChanging();
					this._id_category = value;
					this.SendPropertyChanged("id_category");
					this.Onid_categoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categories_types", DbType="Int NOT NULL")]
		public int id_categories_types
		{
			get
			{
				return this._id_categories_types;
			}
			set
			{
				if ((this._id_categories_types != value))
				{
					if (this._categories_type.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_categories_typesChanging(value);
					this.SendPropertyChanging();
					this._id_categories_types = value;
					this.SendPropertyChanged("id_categories_types");
					this.Onid_categories_typesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_show_on_list", DbType="Bit")]
		public System.Nullable<bool> show_on_list
		{
			get
			{
				return this._show_on_list;
			}
			set
			{
				if ((this._show_on_list != value))
				{
					this.Onshow_on_listChanging(value);
					this.SendPropertyChanging();
					this._show_on_list = value;
					this.SendPropertyChanged("show_on_list");
					this.Onshow_on_listChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tab_filters", DbType="Int NOT NULL")]
		public int id_tab_filters
		{
			get
			{
				return this._id_tab_filters;
			}
			set
			{
				if ((this._id_tab_filters != value))
				{
					if (this._tab_filter.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_tab_filtersChanging(value);
					this.SendPropertyChanging();
					this._id_tab_filters = value;
					this.SendPropertyChanged("id_tab_filters");
					this.Onid_tab_filtersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="category_category_sub", Storage="_category_sub", ThisKey="id_category", OtherKey="id_category_sub", IsUnique=true, IsForeignKey=false)]
		public category_sub category_sub
		{
			get
			{
				return this._category_sub.Entity;
			}
			set
			{
				category_sub previousValue = this._category_sub.Entity;
				if (((previousValue != value) 
							|| (this._category_sub.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._category_sub.Entity = null;
						previousValue.category = null;
					}
					this._category_sub.Entity = value;
					if ((value != null))
					{
						value.category = this;
					}
					this.SendPropertyChanged("category_sub");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="categories_type_category", Storage="_categories_type", ThisKey="id_categories_types", OtherKey="id_categories_types", IsForeignKey=true)]
		public categories_type categories_type
		{
			get
			{
				return this._categories_type.Entity;
			}
			set
			{
				categories_type previousValue = this._categories_type.Entity;
				if (((previousValue != value) 
							|| (this._categories_type.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._categories_type.Entity = null;
						previousValue.categories.Remove(this);
					}
					this._categories_type.Entity = value;
					if ((value != null))
					{
						value.categories.Add(this);
						this._id_categories_types = value.id_categories_types;
					}
					else
					{
						this._id_categories_types = default(int);
					}
					this.SendPropertyChanged("categories_type");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tab_filter_category", Storage="_tab_filter", ThisKey="id_tab_filters", OtherKey="id_tab_filters", IsForeignKey=true)]
		public tab_filter tab_filter
		{
			get
			{
				return this._tab_filter.Entity;
			}
			set
			{
				tab_filter previousValue = this._tab_filter.Entity;
				if (((previousValue != value) 
							|| (this._tab_filter.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tab_filter.Entity = null;
						previousValue.categories.Remove(this);
					}
					this._tab_filter.Entity = value;
					if ((value != null))
					{
						value.categories.Add(this);
						this._id_tab_filters = value.id_tab_filters;
					}
					else
					{
						this._id_tab_filters = default(int);
					}
					this.SendPropertyChanged("tab_filter");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.categories_types")]
	public partial class categories_type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_categories_types;
		
		private string _name;
		
		private int _alias;
		
		private System.Nullable<bool> _show_on_list;
		
		private EntitySet<category> _categories;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_categories_typesChanging(int value);
    partial void Onid_categories_typesChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnaliasChanging(int value);
    partial void OnaliasChanged();
    partial void Onshow_on_listChanging(System.Nullable<bool> value);
    partial void Onshow_on_listChanged();
    #endregion
		
		public categories_type()
		{
			this._categories = new EntitySet<category>(new Action<category>(this.attach_categories), new Action<category>(this.detach_categories));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categories_types", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_categories_types
		{
			get
			{
				return this._id_categories_types;
			}
			set
			{
				if ((this._id_categories_types != value))
				{
					this.Onid_categories_typesChanging(value);
					this.SendPropertyChanging();
					this._id_categories_types = value;
					this.SendPropertyChanged("id_categories_types");
					this.Onid_categories_typesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alias", DbType="Int NOT NULL")]
		public int alias
		{
			get
			{
				return this._alias;
			}
			set
			{
				if ((this._alias != value))
				{
					this.OnaliasChanging(value);
					this.SendPropertyChanging();
					this._alias = value;
					this.SendPropertyChanged("alias");
					this.OnaliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_show_on_list", DbType="Bit")]
		public System.Nullable<bool> show_on_list
		{
			get
			{
				return this._show_on_list;
			}
			set
			{
				if ((this._show_on_list != value))
				{
					this.Onshow_on_listChanging(value);
					this.SendPropertyChanging();
					this._show_on_list = value;
					this.SendPropertyChanged("show_on_list");
					this.Onshow_on_listChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="categories_type_category", Storage="_categories", ThisKey="id_categories_types", OtherKey="id_categories_types")]
		public EntitySet<category> categories
		{
			get
			{
				return this._categories;
			}
			set
			{
				this._categories.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_categories(category entity)
		{
			this.SendPropertyChanging();
			entity.categories_type = this;
		}
		
		private void detach_categories(category entity)
		{
			this.SendPropertyChanging();
			entity.categories_type = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tab_filters")]
	public partial class tab_filter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_tab_filters;
		
		private string _name;
		
		private System.Nullable<bool> _fix;
		
		private EntitySet<category> _categories;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_tab_filtersChanging(int value);
    partial void Onid_tab_filtersChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnfixChanging(System.Nullable<bool> value);
    partial void OnfixChanged();
    #endregion
		
		public tab_filter()
		{
			this._categories = new EntitySet<category>(new Action<category>(this.attach_categories), new Action<category>(this.detach_categories));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tab_filters", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_tab_filters
		{
			get
			{
				return this._id_tab_filters;
			}
			set
			{
				if ((this._id_tab_filters != value))
				{
					this.Onid_tab_filtersChanging(value);
					this.SendPropertyChanging();
					this._id_tab_filters = value;
					this.SendPropertyChanged("id_tab_filters");
					this.Onid_tab_filtersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fix", DbType="Bit")]
		public System.Nullable<bool> fix
		{
			get
			{
				return this._fix;
			}
			set
			{
				if ((this._fix != value))
				{
					this.OnfixChanging(value);
					this.SendPropertyChanging();
					this._fix = value;
					this.SendPropertyChanged("fix");
					this.OnfixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tab_filter_category", Storage="_categories", ThisKey="id_tab_filters", OtherKey="id_tab_filters")]
		public EntitySet<category> categories
		{
			get
			{
				return this._categories;
			}
			set
			{
				this._categories.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_categories(category entity)
		{
			this.SendPropertyChanging();
			entity.tab_filter = this;
		}
		
		private void detach_categories(category entity)
		{
			this.SendPropertyChanging();
			entity.tab_filter = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.category_sub")]
	public partial class category_sub : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_category_sub;
		
		private string _name;
		
		private System.Nullable<bool> _show_on_list;
		
		private int _id_category;
		
		private EntityRef<category> _category;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_category_subChanging(int value);
    partial void Onid_category_subChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onshow_on_listChanging(System.Nullable<bool> value);
    partial void Onshow_on_listChanged();
    partial void Onid_categoryChanging(int value);
    partial void Onid_categoryChanged();
    #endregion
		
		public category_sub()
		{
			this._category = default(EntityRef<category>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_category_sub", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_category_sub
		{
			get
			{
				return this._id_category_sub;
			}
			set
			{
				if ((this._id_category_sub != value))
				{
					if (this._category.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_category_subChanging(value);
					this.SendPropertyChanging();
					this._id_category_sub = value;
					this.SendPropertyChanged("id_category_sub");
					this.Onid_category_subChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_show_on_list", DbType="Bit")]
		public System.Nullable<bool> show_on_list
		{
			get
			{
				return this._show_on_list;
			}
			set
			{
				if ((this._show_on_list != value))
				{
					this.Onshow_on_listChanging(value);
					this.SendPropertyChanging();
					this._show_on_list = value;
					this.SendPropertyChanged("show_on_list");
					this.Onshow_on_listChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_category", DbType="Int NOT NULL")]
		public int id_category
		{
			get
			{
				return this._id_category;
			}
			set
			{
				if ((this._id_category != value))
				{
					this.Onid_categoryChanging(value);
					this.SendPropertyChanging();
					this._id_category = value;
					this.SendPropertyChanged("id_category");
					this.Onid_categoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="category_category_sub", Storage="_category", ThisKey="id_category_sub", OtherKey="id_category", IsForeignKey=true)]
		public category category
		{
			get
			{
				return this._category.Entity;
			}
			set
			{
				category previousValue = this._category.Entity;
				if (((previousValue != value) 
							|| (this._category.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._category.Entity = null;
						previousValue.category_sub = null;
					}
					this._category.Entity = value;
					if ((value != null))
					{
						value.category_sub = this;
						this._id_category_sub = value.id_category;
					}
					else
					{
						this._id_category_sub = default(int);
					}
					this.SendPropertyChanged("category");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
