#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CRM")]
	public partial class DataClassesFiltersDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcategories_type(categories_type instance);
    partial void Updatecategories_type(categories_type instance);
    partial void Deletecategories_type(categories_type instance);
    partial void Inserttab_filter(tab_filter instance);
    partial void Updatetab_filter(tab_filter instance);
    partial void Deletetab_filter(tab_filter instance);
    partial void Insertfilter(filter instance);
    partial void Updatefilter(filter instance);
    partial void Deletefilter(filter instance);
    partial void Insertcategory_sub(category_sub instance);
    partial void Updatecategory_sub(category_sub instance);
    partial void Deletecategory_sub(category_sub instance);
    partial void Insertcategory(category instance);
    partial void Updatecategory(category instance);
    partial void Deletecategory(category instance);
    partial void Insertcategory_filter(category_filter instance);
    partial void Updatecategory_filter(category_filter instance);
    partial void Deletecategory_filter(category_filter instance);
    #endregion
		
		public DataClassesFiltersDataContext() : 
				base(global::CRM.Properties.Settings.Default.CRMConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesFiltersDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesFiltersDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesFiltersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesFiltersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<categories_type> categories_types
		{
			get
			{
				return this.GetTable<categories_type>();
			}
		}
		
		public System.Data.Linq.Table<tab_filter> tab_filters
		{
			get
			{
				return this.GetTable<tab_filter>();
			}
		}
		
		public System.Data.Linq.Table<filter> filters
		{
			get
			{
				return this.GetTable<filter>();
			}
		}
		
		public System.Data.Linq.Table<category_sub> category_subs
		{
			get
			{
				return this.GetTable<category_sub>();
			}
		}
		
		public System.Data.Linq.Table<category> categories
		{
			get
			{
				return this.GetTable<category>();
			}
		}
		
		public System.Data.Linq.Table<category_filter> category_filters
		{
			get
			{
				return this.GetTable<category_filter>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.categories_types")]
	public partial class categories_type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_categories_types;
		
		private string _name;
		
		private int _alias;
		
		private System.Nullable<bool> _show_on_list;
		
		private EntitySet<category> _categories;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_categories_typesChanging(int value);
    partial void Onid_categories_typesChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnaliasChanging(int value);
    partial void OnaliasChanged();
    partial void Onshow_on_listChanging(System.Nullable<bool> value);
    partial void Onshow_on_listChanged();
    #endregion
		
		public categories_type()
		{
			this._categories = new EntitySet<category>(new Action<category>(this.attach_categories), new Action<category>(this.detach_categories));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categories_types", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_categories_types
		{
			get
			{
				return this._id_categories_types;
			}
			set
			{
				if ((this._id_categories_types != value))
				{
					this.Onid_categories_typesChanging(value);
					this.SendPropertyChanging();
					this._id_categories_types = value;
					this.SendPropertyChanged("id_categories_types");
					this.Onid_categories_typesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alias", DbType="Int NOT NULL")]
		public int alias
		{
			get
			{
				return this._alias;
			}
			set
			{
				if ((this._alias != value))
				{
					this.OnaliasChanging(value);
					this.SendPropertyChanging();
					this._alias = value;
					this.SendPropertyChanged("alias");
					this.OnaliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_show_on_list", DbType="Bit")]
		public System.Nullable<bool> show_on_list
		{
			get
			{
				return this._show_on_list;
			}
			set
			{
				if ((this._show_on_list != value))
				{
					this.Onshow_on_listChanging(value);
					this.SendPropertyChanging();
					this._show_on_list = value;
					this.SendPropertyChanged("show_on_list");
					this.Onshow_on_listChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="categories_type_category", Storage="_categories", ThisKey="id_categories_types", OtherKey="id_categories_types")]
		public EntitySet<category> categories
		{
			get
			{
				return this._categories;
			}
			set
			{
				this._categories.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_categories(category entity)
		{
			this.SendPropertyChanging();
			entity.categories_type = this;
		}
		
		private void detach_categories(category entity)
		{
			this.SendPropertyChanging();
			entity.categories_type = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tab_filters")]
	public partial class tab_filter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_tab_filters;
		
		private string _name;
		
		private System.Nullable<bool> _fix;
		
		private EntitySet<category> _categories;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_tab_filtersChanging(int value);
    partial void Onid_tab_filtersChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnfixChanging(System.Nullable<bool> value);
    partial void OnfixChanged();
    #endregion
		
		public tab_filter()
		{
			this._categories = new EntitySet<category>(new Action<category>(this.attach_categories), new Action<category>(this.detach_categories));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tab_filters", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_tab_filters
		{
			get
			{
				return this._id_tab_filters;
			}
			set
			{
				if ((this._id_tab_filters != value))
				{
					this.Onid_tab_filtersChanging(value);
					this.SendPropertyChanging();
					this._id_tab_filters = value;
					this.SendPropertyChanged("id_tab_filters");
					this.Onid_tab_filtersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fix", DbType="Bit")]
		public System.Nullable<bool> fix
		{
			get
			{
				return this._fix;
			}
			set
			{
				if ((this._fix != value))
				{
					this.OnfixChanging(value);
					this.SendPropertyChanging();
					this._fix = value;
					this.SendPropertyChanged("fix");
					this.OnfixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tab_filter_category", Storage="_categories", ThisKey="id_tab_filters", OtherKey="id_tab_filters")]
		public EntitySet<category> categories
		{
			get
			{
				return this._categories;
			}
			set
			{
				this._categories.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_categories(category entity)
		{
			this.SendPropertyChanging();
			entity.tab_filter = this;
		}
		
		private void detach_categories(category entity)
		{
			this.SendPropertyChanging();
			entity.tab_filter = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.filters")]
	public partial class filter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_filters;
		
		private string _name;
		
		private System.Nullable<bool> _active;
		
		private int _index;
		
		private EntitySet<category_filter> _category_filters;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_filtersChanging(int value);
    partial void Onid_filtersChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    partial void OnindexChanging(int value);
    partial void OnindexChanged();
    #endregion
		
		public filter()
		{
			this._category_filters = new EntitySet<category_filter>(new Action<category_filter>(this.attach_category_filters), new Action<category_filter>(this.detach_category_filters));
			OnCreated();
		}

        public filter(string name_)
        {
            this._category_filters = new EntitySet<category_filter>(new Action<category_filter>(this.attach_category_filters), new Action<category_filter>(this.detach_category_filters));
            OnCreated();
            name = name_;
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_filters", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_filters
		{
			get
			{
				return this._id_filters;
			}
			set
			{
				if ((this._id_filters != value))
				{
					this.Onid_filtersChanging(value);
					this.SendPropertyChanging();
					this._id_filters = value;
					this.SendPropertyChanged("id_filters");
					this.Onid_filtersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[index]", Storage="_index", DbType="Int NOT NULL")]
		public int index
		{
			get
			{
				return this._index;
			}
			set
			{
				if ((this._index != value))
				{
					this.OnindexChanging(value);
					this.SendPropertyChanging();
					this._index = value;
					this.SendPropertyChanged("index");
					this.OnindexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="filter_category_filter", Storage="_category_filters", ThisKey="id_filters", OtherKey="id_filter")]
		public EntitySet<category_filter> category_filters
		{
			get
			{
				return this._category_filters;
			}
			set
			{
				this._category_filters.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_category_filters(category_filter entity)
		{
			this.SendPropertyChanging();
			entity.filter = this;
		}
		
		private void detach_category_filters(category_filter entity)
		{
			this.SendPropertyChanging();
			entity.filter = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.category_sub")]
	public partial class category_sub : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_category_sub;
		
		private string _name;
		
		private System.Nullable<bool> _show_on_list;
		
		private System.Nullable<int> _id_category;
		
		private EntityRef<category> _category;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_category_subChanging(int value);
    partial void Onid_category_subChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onshow_on_listChanging(System.Nullable<bool> value);
    partial void Onshow_on_listChanged();
    partial void Onid_categoryChanging(System.Nullable<int> value);
    partial void Onid_categoryChanged();
    #endregion
		
		public category_sub()
		{
			this._category = default(EntityRef<category>);
			OnCreated();
		}

        public category_sub(string name_,int id_category_, bool show_on_list_)
        {
            this._category = default(EntityRef<category>);
            OnCreated();
            name = name_;
            id_category = id_category_;
            show_on_list = show_on_list_;
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_category_sub", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_category_sub
		{
			get
			{
				return this._id_category_sub;
			}
			set
			{
				if ((this._id_category_sub != value))
				{
					this.Onid_category_subChanging(value);
					this.SendPropertyChanging();
					this._id_category_sub = value;
					this.SendPropertyChanged("id_category_sub");
					this.Onid_category_subChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_show_on_list", DbType="Bit")]
		public System.Nullable<bool> show_on_list
		{
			get
			{
				return this._show_on_list;
			}
			set
			{
				if ((this._show_on_list != value))
				{
					this.Onshow_on_listChanging(value);
					this.SendPropertyChanging();
					this._show_on_list = value;
					this.SendPropertyChanged("show_on_list");
					this.Onshow_on_listChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_category", DbType="Int")]
		public System.Nullable<int> id_category
		{
			get
			{
				return this._id_category;
			}
			set
			{
				if ((this._id_category != value))
				{
					if (this._category.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_categoryChanging(value);
					this.SendPropertyChanging();
					this._id_category = value;
					this.SendPropertyChanged("id_category");
					this.Onid_categoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="category_category_sub", Storage="_category", ThisKey="id_category", OtherKey="id_category", IsForeignKey=true)]
		public category category
		{
			get
			{
				return this._category.Entity;
			}
			set
			{
				category previousValue = this._category.Entity;
				if (((previousValue != value) 
							|| (this._category.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._category.Entity = null;
						previousValue.category_subs.Remove(this);
					}
					this._category.Entity = value;
					if ((value != null))
					{
						value.category_subs.Add(this);
						this._id_category = value.id_category;
					}
					else
					{
						this._id_category = default(Nullable<int>);
					}
					this.SendPropertyChanged("category");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.category")]
	public partial class category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_category;
		
		private string _name;
		
		private int _id_categories_types;
		
		private System.Nullable<bool> _show_on_list;
		
		private int _id_tab_filters;
		
		private EntitySet<category_sub> _category_subs;
		
		private EntitySet<category_filter> _category_filters;
		
		private EntityRef<categories_type> _categories_type;
		
		private EntityRef<tab_filter> _tab_filter;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_categoryChanging(int value);
    partial void Onid_categoryChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onid_categories_typesChanging(int value);
    partial void Onid_categories_typesChanged();
    partial void Onshow_on_listChanging(System.Nullable<bool> value);
    partial void Onshow_on_listChanged();
    partial void Onid_tab_filtersChanging(int value);
    partial void Onid_tab_filtersChanged();
    #endregion
		
		public category()
		{
			this._category_subs = new EntitySet<category_sub>(new Action<category_sub>(this.attach_category_subs), new Action<category_sub>(this.detach_category_subs));
			this._category_filters = new EntitySet<category_filter>(new Action<category_filter>(this.attach_category_filters), new Action<category_filter>(this.detach_category_filters));
			this._categories_type = default(EntityRef<categories_type>);
			this._tab_filter = default(EntityRef<tab_filter>);
			OnCreated();
		}

        public category(string  name_)
        {
            this._category_subs = new EntitySet<category_sub>(new Action<category_sub>(this.attach_category_subs), new Action<category_sub>(this.detach_category_subs));
            this._category_filters = new EntitySet<category_filter>(new Action<category_filter>(this.attach_category_filters), new Action<category_filter>(this.detach_category_filters));
            this._categories_type = default(EntityRef<categories_type>);
            this._tab_filter = default(EntityRef<tab_filter>);
            OnCreated();
            name = name_;
        }




        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_category", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_category
		{
			get
			{
				return this._id_category;
			}
			set
			{
				if ((this._id_category != value))
				{
					this.Onid_categoryChanging(value);
					this.SendPropertyChanging();
					this._id_category = value;
					this.SendPropertyChanged("id_category");
					this.Onid_categoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categories_types", DbType="Int NOT NULL")]
		public int id_categories_types
		{
			get
			{
				return this._id_categories_types;
			}
			set
			{
				if ((this._id_categories_types != value))
				{
					if (this._categories_type.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_categories_typesChanging(value);
					this.SendPropertyChanging();
					this._id_categories_types = value;
					this.SendPropertyChanged("id_categories_types");
					this.Onid_categories_typesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_show_on_list", DbType="Bit")]
		public System.Nullable<bool> show_on_list
		{
			get
			{
				return this._show_on_list;
			}
			set
			{
				if ((this._show_on_list != value))
				{
					this.Onshow_on_listChanging(value);
					this.SendPropertyChanging();
					this._show_on_list = value;
					this.SendPropertyChanged("show_on_list");
					this.Onshow_on_listChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tab_filters", DbType="Int NOT NULL")]
		public int id_tab_filters
		{
			get
			{
				return this._id_tab_filters;
			}
			set
			{
				if ((this._id_tab_filters != value))
				{
					if (this._tab_filter.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_tab_filtersChanging(value);
					this.SendPropertyChanging();
					this._id_tab_filters = value;
					this.SendPropertyChanged("id_tab_filters");
					this.Onid_tab_filtersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="category_category_sub", Storage="_category_subs", ThisKey="id_category", OtherKey="id_category")]
		public EntitySet<category_sub> category_subs
		{
			get
			{
				return this._category_subs;
			}
			set
			{
				this._category_subs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="category_category_filter", Storage="_category_filters", ThisKey="id_category", OtherKey="id_category")]
		public EntitySet<category_filter> category_filters
		{
			get
			{
				return this._category_filters;
			}
			set
			{
				this._category_filters.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="categories_type_category", Storage="_categories_type", ThisKey="id_categories_types", OtherKey="id_categories_types", IsForeignKey=true)]
		public categories_type categories_type
		{
			get
			{
				return this._categories_type.Entity;
			}
			set
			{
				categories_type previousValue = this._categories_type.Entity;
				if (((previousValue != value) 
							|| (this._categories_type.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._categories_type.Entity = null;
						previousValue.categories.Remove(this);
					}
					this._categories_type.Entity = value;
					if ((value != null))
					{
						value.categories.Add(this);
						this._id_categories_types = value.id_categories_types;
					}
					else
					{
						this._id_categories_types = default(int);
					}
					this.SendPropertyChanged("categories_type");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tab_filter_category", Storage="_tab_filter", ThisKey="id_tab_filters", OtherKey="id_tab_filters", IsForeignKey=true)]
		public tab_filter tab_filter
		{
			get
			{
				return this._tab_filter.Entity;
			}
			set
			{
				tab_filter previousValue = this._tab_filter.Entity;
				if (((previousValue != value) 
							|| (this._tab_filter.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tab_filter.Entity = null;
						previousValue.categories.Remove(this);
					}
					this._tab_filter.Entity = value;
					if ((value != null))
					{
						value.categories.Add(this);
						this._id_tab_filters = value.id_tab_filters;
					}
					else
					{
						this._id_tab_filters = default(int);
					}
					this.SendPropertyChanged("tab_filter");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_category_subs(category_sub entity)
		{
			this.SendPropertyChanging();
			entity.category = this;
		}
		
		private void detach_category_subs(category_sub entity)
		{
			this.SendPropertyChanging();
			entity.category = null;
		}
		
		private void attach_category_filters(category_filter entity)
		{
			this.SendPropertyChanging();
			entity.category = this;
		}
		
		private void detach_category_filters(category_filter entity)
		{
			this.SendPropertyChanging();
			entity.category = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.category_filters")]
	public partial class category_filter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_category_filters;
		
		private int _id_category;
		
		private int _id_filter;
		
		private EntityRef<category> _category;
		
		private EntityRef<filter> _filter;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_category_filtersChanging(int value);
    partial void Onid_category_filtersChanged();
    partial void Onid_categoryChanging(int value);
    partial void Onid_categoryChanged();
    partial void Onid_filterChanging(int value);
    partial void Onid_filterChanged();
    #endregion
		
		public category_filter()
		{
			this._category = default(EntityRef<category>);
			this._filter = default(EntityRef<filter>);
			OnCreated();
		}


        public category_filter(int id_category_,int id_filter_)
        {
            this._category = default(EntityRef<category>);
            this._filter = default(EntityRef<filter>);
            OnCreated();
            id_category = id_category_;
            id_filter = id_filter_;
        }


        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_category_filters", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_category_filters
		{
			get
			{
				return this._id_category_filters;
			}
			set
			{
				if ((this._id_category_filters != value))
				{
					this.Onid_category_filtersChanging(value);
					this.SendPropertyChanging();
					this._id_category_filters = value;
					this.SendPropertyChanged("id_category_filters");
					this.Onid_category_filtersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_category", DbType="Int NOT NULL")]
		public int id_category
		{
			get
			{
				return this._id_category;
			}
			set
			{
				if ((this._id_category != value))
				{
					if (this._category.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_categoryChanging(value);
					this.SendPropertyChanging();
					this._id_category = value;
					this.SendPropertyChanged("id_category");
					this.Onid_categoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_filter", DbType="Int NOT NULL")]
		public int id_filter
		{
			get
			{
				return this._id_filter;
			}
			set
			{
				if ((this._id_filter != value))
				{
					if (this._filter.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_filterChanging(value);
					this.SendPropertyChanging();
					this._id_filter = value;
					this.SendPropertyChanged("id_filter");
					this.Onid_filterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="category_category_filter", Storage="_category", ThisKey="id_category", OtherKey="id_category", IsForeignKey=true)]
		public category category
		{
			get
			{
				return this._category.Entity;
			}
			set
			{
				category previousValue = this._category.Entity;
				if (((previousValue != value) 
							|| (this._category.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._category.Entity = null;
						previousValue.category_filters.Remove(this);
					}
					this._category.Entity = value;
					if ((value != null))
					{
						value.category_filters.Add(this);
						this._id_category = value.id_category;
					}
					else
					{
						this._id_category = default(int);
					}
					this.SendPropertyChanged("category");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="filter_category_filter", Storage="_filter", ThisKey="id_filter", OtherKey="id_filters", IsForeignKey=true)]
		public filter filter
		{
			get
			{
				return this._filter.Entity;
			}
			set
			{
				filter previousValue = this._filter.Entity;
				if (((previousValue != value) 
							|| (this._filter.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._filter.Entity = null;
						previousValue.category_filters.Remove(this);
					}
					this._filter.Entity = value;
					if ((value != null))
					{
						value.category_filters.Add(this);
						this._id_filter = value.id_filters;
					}
					else
					{
						this._id_filter = default(int);
					}
					this.SendPropertyChanged("filter");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
